### ISSUE TITLE
Zurg not updating rclone mount

### ISSUE THREAD

**Issue by Pukabyte** [debridmediamanager/zurg-testing#10]
- Version: 0.9.2
- zurg http

my configs can be found at: https://puksthepirate.notion.site/puksthepirate/Guide-Zurg-RDT-Prowlarr-Arrs-Petio-Autoscan-Plex-Scannarr-eebe27d130fa400c8a0536cab9d46eb3

Issue:
I use RDT to download symlinks. I've found after starting zurg, rdtclient is able to find the files from rclone for a certain amount of time before zurg becomes unresponsive and stops serving the new information to rclone making rdtclient error out when adding new files.
After restarting zurg and rdtclient (after zurg posts up to rclone) it works again and is able to find all the files like it once did before. however its hard to tell when it starts to not respond as during the whole process zurg reports healthy and still updates the logs every now and then

Things I think it could be:
- rate limiting options in the config
- zurg overloading somehow

**Comment by Pukabyte** [comment]
![image](https://github.com/debridmediamanager/zurg-testing/assets/120460627/a861e05c-4eba-4310-9c5f-bf5eccb78740)
This also shows up. PID=1? Should this be the PID we put in the compose?

**Comment by Merrick28** [comment]
Same here : zurg 0.9.2 using binary on amd64, with rclone (with /dav directory). I have to restart zurg to see the changes made on real-debrid, otherwise, new files don't show in my rclone mount.

**Comment by dreulavelle** [comment]
Issue is also present in the previous hotfix.3 version as well.

**Comment by yowmamasita** [comment]
This should be fixed now on `v0.9.2-hotfix.2`

**Comment by yowmamasita** [comment]
I suppose this is fixed now?

**Comment by Pukabyte** [comment]
Working well! Thanks @yowmamasita
