### ISSUE TITLE
Bug: plex_update.ps1 error

### ISSUE THREAD

**Issue by digitalbarrito** [debridmediamanager/zurg-testing#104]
**Expected Behavior**
No Errors

**Actual Behavior**
Errors

**Detailed Steps**
Detail out everything that you did leading up to the issue.
Include any relevant setup information that we should know about.

Followed this [Guide](https://github.com/ignamiranda/plex_debrid_zurg_scripts/blob/main/README.md)
Getting Errors in my plex_update log. 

**Operating System**
What OS are you running? (e.g., Windows, macOS, Linux): Windows
If on Windows, are you using Windows Subsystem for Linux (WSL)? : No

**Environment Setup**
Are you using Docker, or are you using Zurg's binary?
If Docker, please include your `docker-compose.yml`.
If Zurg's binary, specify the version by running `./zurg version`
zurg.exe version 0.9.3-Hotfix11

**Logs**
Upload your logs by going to http://ZURGIP:9999/logs/upload and paste the link here

[plex_updateErrors.log](https://github.com/debridmediamanager/zurg-testing/files/15049222/plex_updateErrors.log)

If you are running it in Docker, your container logs will also help.

**Rclone Configuration**
Attach or detail your `rclone.conf`.

**Zurg Configuration**
Include your config.yaml or any other relevant configuration files.

[config.yml.txt](https://github.com/debridmediamanager/zurg-testing/files/15049228/config.yml.txt)

**Screenshots**

plex_update.ps1 attached in case it helps
[plex_update - Copy.ps1.txt](https://github.com/debridmediamanager/zurg-testing/files/15049237/plex_update.-.Copy.ps1.txt)

**Comment by yowmamasita** [comment]
Should you instead open an issue on the guide's repo https://github.com/ignamiranda/plex_debrid_zurg_scripts ?

I don't think I can provide support for that
