### ISSUE TITLE
Bug: R Clone writing massive amounts of data to overlay2 volumes

### ISSUE THREAD

**Issue by TBusen** [debridmediamanager/zurg-testing#107]
**Expected Behavior**
To not need 200+ GB of HD space to run this container and have webdav mounted on my server

**Actual Behavior**
When running zurg-testing docker container per the quick start instruction on the main branch README, I notice that my HD is filling up rather quickly.  The webdav mounts and all is good, everything with mounting and consuming from the mounted drive works as expected.  However after about 30 minutes over 30GB of cache data is written to the docker volume overlay2 directories.  This increase in data written only occurs when I start consuming from the mounted webdav.  Until then it is fine.  However even after consumption stops, the cache keeps writing and HD space continues to be taken up.

![image](https://github.com/debridmediamanager/zurg-testing/assets/12953607/babc93e4-9d3f-4305-9fce-51ca61765d61)

![image](https://github.com/debridmediamanager/zurg-testing/assets/12953607/26225481-e4e4-43b4-b895-ec2b56882de8)

**Detailed Steps**
I followed the instructions for Docker exactly.  I've tried this with both the Plex script to run after library update on and commented out in the config.  Both yield the same result as my HD blowing up.

**Operating System**
What OS are you running? (e.g., Windows, macOS, Linux)
Debian 12 Linux, Intel 64

**Environment Setup**
Are you using Docker, or are you using Zurg's binary?
Docker.  I'm using the stock docker-compose.yml that is in the repo.  I only added my RD api token and commented out the Plex script to execute on library update as I'm not using Plex.

**Logs**

https://0x0.st/X8UG.log

**Logs from Docker**
[zurg-testing-latest.log](https://github.com/debridmediamanager/zurg-testing/files/15279980/zurg-testing-latest.log)

I changed the config file extensions to allow them to upload ...

** Docker Compose**
[docker-compose.yml.txt](https://github.com/debridmediamanager/zurg-testing/files/15279839/docker-compose.yml.txt)

**Rclone Configuration**
[rclone.conf.txt](https://github.com/debridmediamanager/zurg-testing/files/15279831/rclone.conf.txt)

**Zurg Configuration**
[config.yml.txt](https://github.com/debridmediamanager/zurg-testing/files/15279843/config.yml.txt)

**Comment by eoghan2t9** [comment]
If you don't need VFS cache you can remove this section of the command from your docker-compose file "--vfs-cache-mode full"

Then find the cache folder for the vfs and delete it then restart your container

**Comment by yowmamasita** [comment]
This is not a zurg issue, you should disable VFS cache or limit the size of your VFS cache - both being rclone issues
