### ISSUE TITLE
Request: support for debrid-link.com

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [debridmediamanager/zurg-testing#108]
**Feature Description**
Hello, there is debrid service that I use called debrid-link.com. I would like to see it supported with zurg! 

**Problem and Motivation**
the issue effects me because I can't use my debrid provider.

**Possible Solution**
support for debrid-link.com as alldebrid and real debrid.

**Alternatives Considered**
web dav and rclone

**Additional Context**
it already supports web dav and rclone, just need to put the config.

**Your Environment**
Debian, docker.

**Potential Impact**
it effects my plex workflow! 

**Preferred Timeline**
asap hopefully 

Remember to follow our contribution guidelines and code of conduct when submitting your request.

**Comment by yowmamasita** [comment]
Supporting other providers in zurg requires massive effort which would probably be best done as another project

**Comment by coccobellof5** [comment]
> Supporting other providers in zurg requires massive effort which would probably be best done as another project

So will you be able to implement this service sooner or later?
It's really good and it seems like a lot of people use it...
Thank you


We would need a simpler system to implement other services.

Something that would take advantage of the webdav and it would be enough to enter only the data necessary for access.
Then zurg does everything else by checking the keywords and sorting into the right folders.

I speak as someone who understands nothing about it, but I hope it can be done, so as to have all the debrids. Thank you!
