### ISSUE TITLE
Request: Debrid-Link

### ISSUE THREAD

**Issue by coccobellof5** [debridmediamanager/zurg-testing#110]
Hello, thank you for this artwork.

I'm sorry to bother you.
Can you implement debrid-link?

https://debrid-link.com/

Excellent alternative to realdebrid and has seedbox support, very convenient for those who don't want to be a parasite and it would be nice to be able to use it with zurg and its features

Thank you

**Comment by yowmamasita** [comment]
https://github.com/debridmediamanager/zurg-testing/issues/108 existing issue
