### ISSUE TITLE
Purpose of the rclone container

### ISSUE THREAD

**Issue by dashed** [debridmediamanager/zurg-testing#111]
Hi, first off, I wanted to say this is awesome! Kudos for putting this together.

This is not a bug report. This is an inquiry on the purpose of the rclone container.

I'm running zurg with docker (ran with `docker compose up -d`), and using rclone to mount http://localhost:9999/dav/ to a local folder, and using plex to load the media from the mounted folder as per the instructions here: https://github.com/debridmediamanager/zurg-testing#how-to-run-zurg-in-5-steps-for-plex-with-docker

I'm curious as to what the purpose of the `rclone` container is, and how it interacts with the `zurg` container. Is this neccessary?

This is the output of my docker logs for the `rclone` container:

```
$ docker logs 62e2465eb6ad # rclone container
2024/06/19 08:24:14 ERROR : /data: Unmounted rclone mount
```

**Comment by Pukabyte** [comment]
That means it was previously unmounted, and or restarted

**Comment by Pukabyte** [comment]
Rclone is what’s mounts the files to the system, zurg does not do this by itself.
