### ISSUE TITLE
Request: Music

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [debridmediamanager/zurg-testing#113]
Hello, as most users know RD rar non media files (like .exe) but in this example RD rar also .mp3 and .flac. IS there a way to overcome this issue with zurg?

I want to add torrent using RDT Client with zurg mounted and RDT download from zurg using it's symlink downloader but each time it fails as it can't symlink rar(s)

**Comment by yowmamasita** [comment]
It is currently supported on the (sponsors-only) v0.10
It will be public once it is deemed stable

**Comment by ianOsborne** [comment]
> It is currently supported on the (sponsors-only) v0.10 It will be public once it is deemed stable

Will this support separate directories for music? As in, will I be able to declare in the config file that I want all .mp3 and .flac to go into a 'Music' folder?

**Comment by yowmamasita** [comment]
Yes that's doable
