### ISSUE TITLE
Bug: Minor issue: zurg output has incorrect instructions on how to control LOG_LEVEL

### ISSUE THREAD

**Issue by shamanNS** [debridmediamanager/zurg-testing#116]
**Expected Behavior**
Describe what you expect to happen.
When starting zurg the output warns that debug logging is enabled and suggests that if user is not currently debugging an issue he should disable that by setting a different logging level via "LOG_LEVEL" environment variable. **It incorrectly stated that you should use "LOG_LEVEL=info" (so "info" in lowercase letters).** 

**Actual Behavior**
Settings the environment variable to "LOG_LEVEL=**info**" doesn't disable debug log messages. Setting it to "LOG_LEVEL=**INFO**" (so value of "INFO", all uppercase letters) does remove debug log messages. 

**Detailed Steps**
See the attached screenshots, what was done and how it was tested is pretty self-evident. 

**Operating System**
What OS are you running? (e.g., Windows, macOS, Linux)
Debain 10 on Raspberry Pi 4.

**Environment Setup**
Are you using Docker, or are you using Zurg's binary?
Not using Docker. Using a standalone zurg binary run as SystemD service.  For the purpose of testing and demonstration of this bug zurg was tested manually via terminal command (see screenshots). 
Zurg version info:

`zurg
Built At: 2024-07-14T09:48:30
Commit: 4179c2745b4fb22fcb37f36de27b3daa39f114f0
Version: v0.9.3-final
`

**Logs**
Not relevant to this minor bug/issue. 

**Rclone Configuration**
Not relevant to this minor bug/issue. 

**Zurg Configuration**
Not relevant to this minor bug/issue. 

**Screenshots**
![Screenshot_20240714_124755_JuiceSSH](https://github.com/user-attachments/assets/2b86c6c2-6cce-4c94-b13b-53309b723142)
![Screenshot_20240714_124851_JuiceSSH](https://github.com/user-attachments/assets/172de0a2-6f23-45f1-8ebe-b326beb95f67)

**Comment by yowmamasita** [comment]
Thanks! For 0.9.3 I won't be able to update this anymore, but I've now fixed this for 0.10

Thanks for reporting!
