### ISSUE TITLE
Bug: Zurg not updating Plex

### ISSUE THREAD

**Issue by wreynolds44** [debridmediamanager/zurg-testing#120]
**Expected Behavior**
The plex_update.ps1 should force a refresh to plex. 
**Actual Behavior**
This is not happening and receiving an inline error message when running the Powershell script. 

**Detailed Steps**
I ran the default Powershell script that i have adjusted with my info. 

**Operating System**
Windows 11 Enterprise x64

**Environment Setup**
Not docker so i am assuming Zurg binary
v0.9.3-final

**Logs**
https://0x0.st/Xxu2.log

**Rclone Configuration**
rclone.confg
[zurg]
type = webdav
url = http://localhost:9999/dav
vendor = other
pacer_min_sleep = 0

[zurghttp]
type = http
url = http://localhost:9999/http
no_head = false
no_slash = false

**Zurg Configuration**
![image](https://github.com/user-attachments/assets/89582e8d-4564-454e-b8b0-b6d371685371)
I left the token empty as i don't want others to have it. 
**Screenshots**
![image](https://github.com/user-attachments/assets/4b0a0d21-b80d-4b6c-a10e-85e56b3360b2)
The token in the .yml and Powershell script are the same, i double checked before uploading.

**Comment by shamanNS** [comment]
@wreynolds44 

>The token in the .yml and Powershell script **are the same**, i double checked before uploading.

And there lies your problem ;) "token" in config.yml and "token" in the PowerShell script refer to 2 different things:

1) in config.yml you add RD token. 
2) in PowerShell updater script the "token" expected is Plex Token, associated with that logged in Plex user account. The script uses that to authorise Plex API requests.

**Comment by wreynolds44** [comment]
@shamanNS my apologies i meant to say the match their correct token. config.yml having the RD token and the powershell token having the plex token.

**Comment by wreynolds44** [comment]
Never mind this can be closed, looks like I needed to wait longer for Zurg to run before it started forcing the refresh.
