### ISSUE TITLE
Request:

### ISSUE THREAD

**Issue by Reasonable-Grape2698** [debridmediamanager/zurg-testing#123]
**Feature Description**
Add /Music folder

**Problem and Motivation**
Music files are supported by both debrid and plex, though not included in zurg. They simply go to __unplayable__ 

**Possible Solution**
I couldn't get it to work but the below regex correctly filters mp3, m4a, flac and wav. I believe it may not work because the .* above in movies takes over.
``` /.*mp3|.*m4a|.*flac|.*wav/``` 

**Alternatives Considered**
Adding __unplayable__ as the music library?

**Additional Context**

**Your Environment**
Linux w/ plex, rclone, zurg

**Potential Impact**
Unable to support music files

**Preferred Timeline**
Should be easy change hopefully

Remember to follow our contribution guidelines and code of conduct when submitting your request.

**Comment by Reasonable-Grape2698** [comment]
![image](https://github.com/user-attachments/assets/3d82c34c-8062-46f5-8cfb-417fabd8d885)

**Comment by Reasonable-Grape2698** [comment]
May be a support request not a feature request, but according to docs there's no reason this shouldn't work?

**Comment by yowmamasita** [comment]
this is now natively supported in zurg v0.10

there is a `is_music` filter
