### ISSUE TITLE
xmllint on Synology NAS

### ISSUE THREAD

**Issue by chrisdavies76** [debridmediamanager/zurg-testing#15]
Hey, I have this zurg-testing all working on my Synology DS918+ NAS apart from the plex_update.sh script. This part does not work as I don't have the xmllint command on this host and it's not trivial to get it on afaik. 

Error is -sh: xmllint: command not found

is there a way of getting this to work on hosts without xmllint?

Thanks

**Comment by yowmamasita** [comment]
Try

docker compose exec zurg apk add xmllint

**Comment by chrisdavies76** [comment]
Hey thanks for the response and suggestion and also the great work on this project, tried as you suggested and sadly it doesn't work either:

chris@DS918Plus:~/zurg-testing-main$ docker-compose exec zurg apk add xmllint
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  xmllint (no such package):
    required by: world[xmllint]
ERROR: 1
chris@DS918Plus:~/zurg-testing-main$ 


Any other ideas? Something to do with alpine linux repositories within the container I'm guessing but how to fix that I'm not sure :-/

Thanks again

**Comment by NebKi** [comment]
They are part of libxml2-utils package. I think you need to install that first: https://pkgs.alpinelinux.org/packages?name=libxml2-utils&branch=v3.19&repo=main&arch=&maintainer=

**Comment by yowmamasita** [comment]
`docker compose exec zurg apk add libxml2-utils`

**Comment by chrisdavies76** [comment]
hey, thanks again. So that works and sorts that problem out. When running plex_update.sh script from within the container to test check its working I get this: 

<code>
chris@DS918Plus:~/zurg-testing-main$ docker-compose exec zurg sh
/app # ls
config.yml      data            healthcheck.sh  logs            plex_update.sh  zurg
/app # sh plex_update.sh 
-:1: parser error : Document is empty

^
All updated sections refreshed
/app # 
</code>

Does that look right?

**Comment by chrisdavies76** [comment]
xmllint not found issue now sorted thanks for the help.

**Comment by alexdelprete** [comment]
> `docker compose exec zurg apk add libxml2-utils`

so it is missing in the alpine docker image. will you include it?
