### ISSUE TITLE
Exec format error on arm64 + docker

### ISSUE THREAD

**Issue by ebai101** [debridmediamanager/zurg-testing#18]
I'm trying to use the docker image on my Arm box, but I can't seem to get a working image from the repo. When I try to run a container with the image it shows me this:

```
$ docker run ghcr.io/debridmediamanager/zurg-testing:latest
exec ./zurg: exec format error
$ uname -m
aarch64
```

The linux-arm64 executable from the releases folder works fine for me, but I'd like to run it in a container for networking purposes.

**Comment by lostb1t** [comment]
only the docker image is arm64, the zurg executable doesn’t seem to be compiled for arm64 hence the error.

Would be nice if this can be fixed. running on arm as well.

**Comment by ebai101** [comment]
FWIW, I managed to get a rudimentary container working with this Dockerfile. I'm not sure if it's 100% functional, but it seems to run OK.
```
FROM alpine:latest
CMD mkdir /app
WORKDIR /app

# using the latest linux-arm64 release from github
COPY ./zurg .

# gcompat is definitely needed, curl and python3 i believe are used for the healthcheck script
RUN apk add --no-cache curl python3 gcompat

ENTRYPOINT ./zurg
```

Build and run:
```
docker build -t zurg-aarch64 .
docker run -v ./config.yml:/app/config.yml zurg-aarch64
```

**Comment by yowmamasita** [comment]
I have found out the issue on the arm build for zurg's image. I will fix it asap

**Comment by herobrauni** [comment]
In case others with this Problem are following this issue. It seems to be fixed with the latest commit and you can use "zurg:latest" again on arm.
Thanks a lot for the quick fix !

**Comment by yowmamasita** [comment]
Yes it is now fixed on the :latest tag!
