### ISSUE TITLE
folder name

### ISSUE THREAD

**Issue by laster13** [debridmediamanager/zurg-testing#2]
Is it possible to display only files and not folders in "ALL MY STUFFS" with regex filters?
I think that would make RDT symlinks work better, which in my opinion has difficulty creating symlinks because of the recursion of folders;

Also what I see

with webdav and zurg , torrent folders  are named exactly the same as mkv files, this is possibly one of the reasons why symlinks are done quickly and without errors

[zurg]
type = webdav
url = https://laster13:BxxxxxxxTU@dav.real-debrid.com/
vendor = other
user = laster13
pass = OxxxxxxxxxxxxxOCS-T1xiGOaU_TCu-j-lUQduA

real    0m2.976s
user    0m0.061s
sys     0m0.045s
167

real    0m0.164s
user    0m0.066s
sys     0m0.033s
167

real    0m0.157s
user    0m0.063s
sys     0m0.036s

with zurg and rclone. conf http, folders  are not named like files and i have simlink error

[zurg]
type = http
url = http://zurg:9999/http
no_head = false
no_slash = false

root@ubuntu:~# (for i in {1..10}; do time (docker compose exec rclone ls -1R /data | wc -l); done)
266

real    0m0.243s
user    0m0.079s
sys     0m0.025s
266

real    0m0.193s
user    0m0.089s
sys     0m0.018s

also the question is webdav with zurg limited in number of files?

**Comment by joshk6656** [comment]
I think the real solution here is to fix the folder name, not display just the files.

RDT symlink expects the EXACT same folder structure as a normal webdav mount.

attaching your images from discord to make this more obvious.
![image](https://github.com/debridmediamanager/zurg-testing/assets/489101/d79713d5-e026-478e-9f89-0b7fdd9ced93)

![image](https://github.com/debridmediamanager/zurg-testing/assets/489101/7d4029a2-5f49-433d-878b-2bc8709546c5)

**Comment by laster13** [comment]
Works with a modification of RDT thanks

**Comment by joshk6656** [comment]
I don't think this should be closed, it is an issue that the folder structure doesn't match. The goal i believe is a faster webdav mount, so it should be identical?

**Comment by godver3** [comment]
> I don't think this should be closed, it is an issue that the folder structure doesn't match. The goal i believe is a faster webdav mount, so it should be identical?

Agreed. The RDT fix is a workaround - ideally Zurg can provide folders with a matching format, even if just as an option.

**Comment by yowmamasita** [comment]
Will fix!

**Comment by yowmamasita** [comment]
It is now fixed on the image

```
docker pull ghcr.io/debridmediamanager/zurg-testing:v0-defuse
```

This is the interim image before the standalone version of zurg comes out

I've also updated the wiki https://github.com/debridmediamanager/zurg-testing/wiki/Config

**Comment by yowmamasita** [comment]
Will close now since it's fixed! Thank you guys
