### ISSUE TITLE
32 bit support? 

### ISSUE THREAD

**Issue by lennon1997** [debridmediamanager/zurg-testing#22]
Any plans to compile for 32 bit armv7? I am trying to run on Raspberry Pi 2 Model B Rev 1.1 but receiving exec ./zurg: exec format error

**Comment by yowmamasita** [comment]
The arm images are broken but I will fix it the soonest I get back from vacation :) I'll respond here once it is fixed

**Comment by yowmamasita** [comment]
I'm building the arm/v7 image now, it should come very soon

**Comment by yowmamasita** [comment]
https://github.com/debridmediamanager/zurg-testing/tree/main/releases/v0.9.2-hotfix.4-32bit

docker pull ghcr.io/debridmediamanager/zurg-testing:v0.9.2-hotfix.4-32bit
