### ISSUE TITLE
Can't find the zurg source code, only the built images..

### ISSUE THREAD

**Issue by neaumusic** [debridmediamanager/zurg-testing#23]
Is the zurg source code publicly available anywhere? I see the `config.yml` but have no idea how the variables are used or what's running internally, am I missing something?

**Comment by Pukabyte** [comment]
Not open sourced, you'll need to support to get access

**Comment by maxexcloo** [comment]
> Not open sourced, you'll need to support to get access

How can I support? I'd prefer to see the code I'm running if I can :)

**Comment by funkypenguin** [comment]
You can [sponsor](https://github.com/sponsors/debridmediamanager) to support and get access to the sekritz :)
