### ISSUE TITLE
support for raspberry pi

### ISSUE THREAD

**Issue by sasagr** [debridmediamanager/zurg-testing#28]
It seems that raspberry pi is not supported. Could you add it?

pi@raspberrypi:~/zurg-testing $ docker-compose up -d
Creating network "zurg-testing_default" with the default driver
Creating volume "zurg-testing_zurgdata" with default driver
Pulling zurg (ghcr.io/debridmediamanager/zurg-testing:latest)...
latest: Pulling from debridmediamanager/zurg-testing
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

**Comment by yowmamasita** [comment]
Ah let me add this too

**Comment by yowmamasita** [comment]
https://github.com/debridmediamanager/zurg-testing/tree/main/releases/v0.9.2-hotfix.4-32bit

docker pull ghcr.io/debridmediamanager/zurg-testing:v0.9.2-hotfix.4-32bit
