### ISSUE TITLE
Is it possible to expose /links

### ISSUE THREAD

**Issue by kudddyyy** [debridmediamanager/zurg-testing#30]
The previous tool could expose not only the torrent but also the debrided links from /links

Is it possible too here ?

**Comment by yowmamasita** [comment]
It's coming on the next version

**Comment by yowmamasita** [comment]
Released https://github.com/debridmediamanager/zurg-testing/wiki/zurg-is-now-v0.9.3-old

**Comment by kudddyyy** [comment]
It seems that files are not played when selected from this folder. It just hangs. In the logs I get errors like 


`2024-01-25T23:24:29.863+0100	WARN	manager	Cannot unrestrict link https://42.download.real-debrid.com/d/MCO52SX43RTLS/Spiderman.2002.REMASTERED.1080p.BluRay.H264.AAC-RARBG.mp4: unrestrict link request failed: Post "https://api.real-debrid.com/rest/1.0/unrestrict/link": dial tcp 94.140.4.10:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
`

**Comment by kudddyyy** [comment]
@yowmamasita This feature seems gone in the last release ?

**Comment by yowmamasita** [comment]
`enable_download_mount: true`
