### ISSUE TITLE
Request: Jellyfin 

### ISSUE THREAD

**Issue by arjung24** [debridmediamanager/zurg-testing#31]
Please add how can we use zurg with jellyfin. It would be very much helpful. Thanks 🙏

**Comment by Pukabyte** [comment]
Just map the libraries to zurg?

**Comment by yowmamasita** [comment]
@arjung24 what are you looking for? a guide?

**Comment by arjung24** [comment]
> @arjung24 what are you looking for? a guide?

Yes brother 🙏🙏

**Comment by n0gg3r** [comment]
@arjung24
Just follow the guide for zurg in the github repo.
After setting up zurg edit the rclone config so it says localhost:9999 and then just mount it and map the libraries to this path.

**Comment by arjung24** [comment]
> @arjung24 Just follow the guide for zurg in the github repo. After setting up zurg edit the rclone config so it says localhost:9999 and then just mount it and map the libraries to this path.

Do i need a vps for this or i can do that with termux locally?

**Comment by Pukabyte** [comment]
> > @arjung24 what are you looking for? a guide?
> 
> 
> 
> Zurg run command ./zurg saying permission denied
> 
> I am running zurg on vps
> 
> ![IMG_20240114_223946](https://github.com/debridmediamanager/zurg-testing/assets/68998000/baa7ec1f-e6e7-4d19-928b-3bf8b84da935)
> 
> ![IMG_20240115_112626](https://github.com/debridmediamanager/zurg-testing/assets/68998000/253af5ec-22fc-4df8-9564-49d57c0b74e1)

Not sure what you're trying to do there, cd into the zurg directory and then: docker compose up -d

It'll load up the docker container and mount the drive. Make sure to make changes to the config.yml and docker-compose.yml for your use case

**Comment by waiyanminthant** [comment]
Seems like you don't have execute permission. Try making the file executable. 

`chmod +x ~/zurg-testing/zurg` ?

**Comment by yowmamasita** [comment]
I'm gonna close this issue, the setup for Jellyfin is the same as Plex.
