### ISSUE TITLE
Request: Wiki documentation update

### ISSUE THREAD

**Issue by Varming73** [debridmediamanager/zurg-testing#34]
I didn't want to report this as a bug but it would be nice to have the documentation updated with the options for the config file and the new commandline options.

**Comment by yowmamasita** [comment]
On it!

**Comment by yowmamasita** [comment]
https://github.com/debridmediamanager/zurg-testing/wiki/Config I've updated this page

**Comment by maxexcloo** [comment]
> https://github.com/debridmediamanager/zurg-testing/wiki/Config I've updated this page

Does it have every new option now? Looks great 👍🏻

**Comment by yowmamasita** [comment]
Closing this, it's already resolved. Updated to the latest version.
