### ISSUE TITLE
Bug: worker exits from panic (0.9.3)

### ISSUE THREAD

**Issue by Varming73** [debridmediamanager/zurg-testing#36]
After upgrading to 0.9.3 I see this in the log which I guess is a bug:

`2024/01/16 21:15:01.184637 [ants]: worker exits from panic: runtime error: invalid memory address or nil pointer dereference
goroutine 5611 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.8.2/worker.go:56 +0x85
panic({0x918760?, 0xdd8e00?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:83
github.com/debridmediamanager/zurg/internal/torrent.(*TorrentManager).Repair.func2()
        /app/internal/torrent/repair.go:124 +0xc8
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.8.2/worker.go:67 +0x8d
created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 5366
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.8.2/worker.go:48 +0x5c`

I see it several times after running just a few minuts.

**Comment by yowmamasita** [comment]
Please test `v0.9.3-hotfix.1` I've fixed this
