### ISSUE TITLE
Bug: Media files with whitespace in the filenames don't work

### ISSUE THREAD

**Issue by CokeZeroConsumer** [debridmediamanager/zurg-testing#38]
**Expected Behavior**
Filenames with whitespace should still be parsed & loaded

**Actual Behavior**
They're not.

**Detailed Steps**
On v0.9.2-hotfix4, no such issue exists.
On v0.9.3, it errors out in the logs saying it can't find the torrent.
Reverting to the old(er) version resolves the issue.

**Repro example**
Attempt to load any file with whitespace characters and the request will fail
"My Show S01E01 - Title.mkv" => fails
"My.Show.S01E01-Title.mkv" => succeeds

**Operating System**
Ubuntu 22.04

**Environment Setup**
Docker with standard `docker-compose.yml`

**Rclone Configuration**
Standard `rclone.conf`

**Zurg Configuration**
Standard `config.yml`

**Comment by yowmamasita** [comment]
Please test `v0.9.3-hotfix.1` I've fixed this
