### ISSUE TITLE
Bug: [ants]: worker exits from panic (0.9.3hotfix1)

### ISSUE THREAD

**Issue by Varming73** [debridmediamanager/zurg-testing#39]
This is still an issue on 0.9.3hotfix1:

2024-01-20T15:12:43.626Z        INFO    manager Attempting repair for torrent Dance Moms Season 1-7 Complete 1080p HDTV x264
2024-01-20T15:12:43.704Z        INFO    manager Finished checking for broken torrents
2024-01-20T15:12:43.704Z        INFO    manager Checking for broken torrents
2024-01-20T15:12:43.704Z        INFO    manager Started repair process for torrent Dance Moms Season 1-7 Complete 1080p HDTV x264
2024/01/20 15:12:46.056833 [ants]: worker exits from panic: runtime error: index out of range [416] with length 223
goroutine 607053 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.8.2/worker.go:56 +0x85
panic({0x978cc0?, 0xc0008064f8?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/debridmediamanager/zurg/internal/torrent.(*TorrentManager).isStillBroken(0xc0001cc0f0?, 0xc002d120c0, {0xc000bd8000, 0x1, 0xff?})
        /app/internal/torrent/repair.go:432 +0x19b
github.com/debridmediamanager/zurg/internal/torrent.(*TorrentManager).repair(0xc0001cc0f0, 0xc00140e410)
        /app/internal/torrent/repair.go:245 +0xdce
github.com/debridmediamanager/zurg/internal/torrent.(*TorrentManager).Repair.func2()
        /app/internal/torrent/repair.go:150 +0x25
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.8.2/worker.go:67 +0x8d
created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 353651
        /go/pkg/mod/github.com/panjf2000/ants/v2@v2.8.2/worker.go:48 +0x5c

2024-01-20T15:12:59.152Z        INFO    manager Detected changes! Refreshing 5229 torrents

**Comment by yowmamasita** [comment]
Thanks for reporting early, fixing now

**Comment by yowmamasita** [comment]
Pushed the fix, building now. I'll close this
