### ISSUE TITLE
Bad Gateway Errors in Rclone

### ISSUE THREAD

**Issue by godver3** [debridmediamanager/zurg-testing#4]
Using rclone (through the Docker-Compose file) I am seeing errors in the rclone log:

```
</html>: 502 Bad Gateway
2023/11/05 02:00:13 ERROR : IO error: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>: 502 Bad Gateway
```

I don't know if these errors are associated with anything - perhaps they happen when an unfixable link is encountered? I am not sure.

**Comment by yowmamasita** [comment]
@godver3 it is possible. Unfortunately with the log provided I am not able to know which URL this is coming from
