### ISSUE TITLE
Bug: Logic changed 

### ISSUE THREAD

**Issue by Varming73** [debridmediamanager/zurg-testing#42]
With the latest 0.9.3hotfix1 the logic has somehow changed when something is repaired. A lot of old stuff suddenly shows up as Recently Added in Plex which never happend with 0.9.2hotfix4. This messes up everything related to keeping track of what is added - the Plex screens, notifications etc.

**Comment by Varming73** [comment]
Is this fixable at all? I know it can take some time but if it can't be fixed I have to ditch my setup as the Recently Added in Plex is unusable as is now. A lot of old stuff is being pushed and you have no idea what has been added to the server any longer.

I don't write this to press for a solution (maybe a bit) but mainly as it will take me some time to find a serious, different solution - whether it's stop using RD, start using a different application or whatever.

Is it better to use 0.9.2hotfix4 for now?

**Comment by yowmamasita** [comment]
This should be fixed on `v0.9.3-hotfix.3`
