### ISSUE TITLE
Bug: MacOS issue

### ISSUE THREAD

**Issue by Cristianepv96** [debridmediamanager/zurg-testing#48]
When trying to sudo mkdir -p /mnt/zurg
I keep getting mkdir: /mnt: Read-only file system on MacOS 14.2.1 (23C71) Sonoma. 
How I can solve this? I can't find guides(for noobs) to solve.

**Comment by yowmamasita** [comment]
@Cristianepv96 you can do it in your home folder instead

just use $HOME/zurg for example

**Comment by Cristianepv96** [comment]
What line I need to change, I tried but I'm not sure what was wrong

**Comment by yowmamasita** [comment]
on your rclone mount command

are you planning to use docker / docker-compose?

**Comment by Cristianepv96** [comment]
Yes, i´m trying to follow this instructions: 
Clone this repo git clone https://github.com/debridmediamanager/zurg-testing.git
Add your token in config.yml
sudo mkdir -p /mnt/zurg
Run docker compose up -d
time ls -1R /mnt/zurg You're done! If you do edits on your config.yml just do docker compose restart zurg.

Thank u for your response, i'm just noob at this and if something doesn't work or need something additional just can't get it work.

**Comment by Cristianepv96** [comment]
Can I use /Users/mac/Downloads/zurg-testing-main/realdebrid?

**Comment by yowmamasita** [comment]
Yes @Cristianepv96 you can use anything
