### ISSUE TITLE
File Repair Improvement

### ISSUE THREAD

**Issue by godver3** [debridmediamanager/zurg-testing#5]
If a file is un-repairable it might be helpful to improve the logic to either:

- Ideally find a different version of the same movie/TV show (which I believe is attempted, but not sure to what extent)
- Delete the torrent from RD to allow something like Plex-Debrid or alternative to find a different file

**Comment by yowmamasita** [comment]
> Delete the torrent from RD to allow something like Plex-Debrid or alternative to find a different file

I think I will go ahead with this solution instead

**Comment by dreulavelle** [comment]
Out of curiosity, how is rclone_rd handling repairs?

**Comment by yowmamasita** [comment]
3 conditions:

1. https://github.com/itsToggle/rclone_RD/blob/master/backend/realdebrid/realdebrid.go#L721
2. https://github.com/itsToggle/rclone_RD/blob/master/backend/realdebrid/realdebrid.go#L1219
3. https://github.com/itsToggle/rclone_RD/blob/master/backend/realdebrid/realdebrid.go#L630

It then redownloads the parent torrent.

**Comment by yowmamasita** [comment]
This is already fixed!
