### ISSUE TITLE
Request: Duplicate torrent deletion 

### ISSUE THREAD

**Issue by kudddyyy** [debridmediamanager/zurg-testing#50]
**Feature Description**
It would be nice to have a way to delete duplicate torrents from the real-debrid interface.

**Problem and Motivation**
In a previous bug, all my torrents were incorrectly sent for repair, meaning that now I have 56 pages of torrents, most of them being duplicates.

**Possible Solution**
Since zurg already loads all the torrents, and has an option to clear all torrents, some easy filtering would allow to clean duplicates.

**Comment by yowmamasita** [comment]
Hi @kudddyyy 

In https://debridmediamanager.com/library you can click on "Same title/ hash" and then click on "🧹 Hash"

<img width="583" alt="image" src="https://github.com/debridmediamanager/zurg-testing/assets/1567724/010047f1-aebe-48dd-b458-7edb7ca81f1b">

**Comment by kudddyyy** [comment]
Thanks !
