### ISSUE TITLE
Bug: Zurg shows file as unavailble but it's playable on real-debrid

### ISSUE THREAD

**Issue by deepvalu** [debridmediamanager/zurg-testing#51]
For some reason this file in the torrent pack below cannot be found by zurg

Cannot find file  from path /dav/shows/South Park - Seasons 1 to 25 (S01-S25) Master Collection, The Movie & Extras [1080p-2160p NVEnc 10Bit HEVC][TrueHD+DDP 5.1Ch][English Subs]/South Park - S15E12 - 1%.mkv

https://debridmediamanager.com/hashlist#NobwRAZglgNgpgOwIYFs5gFxgMoHsCuALgBYAEACkgE4DWpAtKdnEgM64KukCMphupAEwBWUgApsABm71sIgJSkAsm0JwqpAMK4Y8AMaEoHADSkAKsTjLcANyhWAZKQCiAD0JU2pYN0kAOSQAHekFuADYg0gA5ADVnBD0eSQAhKEJSAAlnGM0AXWAzKnw4DIARAGpS0vJSYQA6bk1ifPiAcxgoVjJsfAAjVlywYzBiNmJMMABmPWFJJABOODCIgHYV3ulJwUkAFhX58IhBODg-MMEIPfCkABMIYXmhsF6ATzVWTEFJ4R3fecEdltuABfXJAA

**Detailed Steps**
Detail out everything that you did leading up to the issue.
Include any relevant setup information that we should know about.

**Operating System**
Ubuntu

**Environment Setup**
Zurg Binary AMD 64 v0.9.3-hotfix.2 published 1/24/2024
[zurg config.pdf](https://github.com/debridmediamanager/zurg-testing/files/14040652/zurg.config.pdf)
[
[logs.txt](https://github.com/debridmediamanager/zurg-testing/files/14040664/logs.txt)
](url)

**Rclone Configuration**
Attach or detail your `rclone.conf`.

**Zurg Configuration**
Include your config.yaml or any other relevant configuration files.

**Screenshots**

**Comment by yowmamasita** [comment]
I think it's because of the 1% in the filename, let me check this!

**Comment by yowmamasita** [comment]
This is fixed on the latest release!
