### ISSUE TITLE
Source Code?

### ISSUE THREAD

**Issue by Friday13th87** [debridmediamanager/zurg-testing#53]
Hello!
May i ask where the actual source code of the zurg app is?
I can only find the compiled zurg apps for the different releases but not the actual source code.
thanks

***

@yowmamasita: I am sorry @Friday13th87 but I will hijack your post and add the direct link to my response: https://github.com/debridmediamanager/zurg-testing/issues/53#issuecomment-1919615552

**Comment by b4154** [comment]
Same. It's weird that this project is on github but it's closed source.

**Comment by ignamiranda** [comment]
You can find the source code here if you donate to the project https://github.com/debridmediamanager/zurg

**Comment by b4154** [comment]
> You can find the source code here if you donate to the project https://github.com/debridmediamanager/zurg

Where do I donate? Patreon? Or through GitHub?

**Comment by Friday13th87** [comment]
Thanks for the information @ignamiranda 
So on the 4$ tier the actual source code is available or just another compiled binary?

This information would be worth mentioning in the Readme ;D

**Comment by yowmamasita** [comment]
I'd like to clarify the reasons behind the "hidden" status of zurg's source code. Firstly, I am not currently open to forks of my work; this is to maintain a singular vision and coherence in the project's development. Secondly, as an extension of the first reason, given that zurg is in its early beta stage, any code alterations might become obsolete as the project evolves, and I wish to spare others the effort of potentially sending me pull requests. Finally, as an adequate developer, I'm conscious of my coding style, and I prefer to avoid critiques of my work.

It's important to note that zurg is not a paid software. Access to it isn't a product to be sold. My intention is never to charge for its use. This is to avoid the "complexities" that arise with users who might feel entitled to a certain standard or functionality, especially when dealing with software still in development.

If you choose to support me or zurg and send me your hard-earned money every month here on Github or Patreon, I hope it's about your genuine interest in and commitment to supporting my hobby projects and not about just transactional access to source code.

**Comment by b4154** [comment]
> If you choose to support me or zurg and send me your hard-earned money every month here on Github or Patreon, I hope it's about your genuine interest in and commitment to supporting my hobby projects and not about just transactional access to source code.

Of course! I currently use zurg in my Plex setup and it works flawlessly so far. I rely on it for my Plex setup and I was genuinuely interested in how it worked under the hood, so I decided to donate to help support the project.

**Comment by yowmamasita** [comment]
I will now close this issue. I've highlighted my response on the readme.
