### ISSUE TITLE
Log level is high in v0.9.3-hotfix.2

### ISSUE THREAD

**Issue by Varming73** [debridmediamanager/zurg-testing#55]
When I look at the logs from v0.9.3-hotfix.2 there is way too much information. According the to Wiki there is no config setting to adjust the log levels. Could that be added or logging level lowered?

**Comment by yowmamasita** [comment]
it can be with `LOG_LEVEL` env var (INFO, WARN, etc.)

**Comment by DavidOBE** [comment]
How do you use this? Is it a line in the config file?

I tried LOG_LEVEL: INFO, but it didn't work.

Would like to also limit the amount of data in the log, but not sure how to do this in the env var??

Thanks!
