### ISSUE TITLE
Newbie questione about Plex synchronizing

### ISSUE THREAD

**Issue by puppinoo** [debridmediamanager/zurg-testing#56]
Hi,
Sorry if the question Is stupid but I setup zurg + vanilla rclone (not rclone_rd) on my VPS.
Everything works fine if I send link through DMM but when I add a content to my watchlist in Plex nothing happens. Is this normal? When I setup rclone_rd It monitored my Plex watchlist and added content.
I also uncommented the call to plex_update.sh,
RD folder Is mounted and I can see folders inside.
Am I missing anything here? Maybe to make Plex act as an agent I need to add software or configurazion?

Thanks and sorry for probably wasting your time.

**Comment by funkypenguin** [comment]
Yes, it's normal - zurg doesn't do anything with your Plex watchlist, it only monitors changes to RD.

You'll want either [plex_debrid](https://github.com/itsToggle/plex_debrid), or [iceberg](https://github.com/dreulavelle/iceberg) :)

**Comment by puppinoo** [comment]
I got It.
I used PD in the past but was too unstable. Ill check out your advices
about it again and iceberg too.
Thanks a lot.

Il sab 27 gen 2024, 12:01 David Young ***@***.***> ha scritto:
