### ISSUE TITLE
Bug: check for changes doesn't do anything after a while

### ISSUE THREAD

**Issue by Varming73** [debridmediamanager/zurg-testing#58]
Using 0.9.3.hotfix3 commit a46e7df with config ´check_for_changes_every_secs: 15´changes are triggering an update at first but after some hours this seems to stop working. With log level DEBUG nothing helpful is seen in the logs.

**Comment by yowmamasita** [comment]
I've figured out the issue. The checksum if it fails (because of api timeout) will crash the refresh job. I'll send a fix soon.

**Comment by yowmamasita** [comment]
The workaround is to increase the api_timeout_secs to 60

**Comment by Varming73** [comment]
As the updates to the drive aren't detected RDT seems to fail and redownload. So am getting dublicates at the moment (even after increasing the timeout to 60). With Debrid Media Manager I can see the downloads as completed but not in the Zurg mount.

**Comment by yowmamasita** [comment]
<img width="711" alt="image" src="https://github.com/debridmediamanager/zurg-testing/assets/1567724/ee378b19-cc6d-4f4c-af7a-29180c2ca7ac">

I've added this, also changed the defaults for timeouts
