### ISSUE TITLE
Bug:Shows removed from Zurg mount

### ISSUE THREAD

**Issue by fatbob01** [debridmediamanager/zurg-testing#60]
**Expected Behavior**
Plex scan to complete successfully

**Actual Behavior**
Shows are removed from zurg mount even though they are present in debrid manager and are never re-added.

**Detailed Steps**
Start scan from plex tv shows, items already present in zurg get removed and are never re-added.

**Operating System**
What OS are you running? (e.g., Windows, macOS, Linux) Windows
If on Windows, are you using Windows Subsystem for Linux (WSL)? N

**Environment Setup**
Are you using Docker, or are you using Zurg's binary? Binary
If Docker, please include your `docker-compose.yml`.
If Zurg's binary, specify the version by running `./zurg version`

Release v0.9.3-hotfix.3

Config:

# Zurg configuration version
zurg: v1
token: x

# do not change this if you are running it inside a docker container
host: "[::]"
port: 9999

# you can protect your zurg server with username+password auth
# username: yowmamasita
# password: 1234

# You can proxy all zurg requests like this:
# proxy: "http://[username:password@]host:port"
# proxy: "https://[username:password@]host:port"
# proxy: "socks5://[username:password@]host:port"

# How many requests in parallel should we send to Real-Debrid API?
concurrent_workers: 50

# How often should we check Real-Debrid API for file changes?
check_for_changes_every_secs: 10

# if true, saved rename info (if it exists) will be ignored
ignore_renames: false

# if true, it will strictly follow Real-Debrid API filename property
# setting to true should make zurg more compatible with rdt-client
retain_rd_torrent_name: false

# note: this is for cosmetic purposes only
# if true, zurg won't drop file extensions from directories
retain_folder_name_extension: false

# if true, zurg will delete Real-Debrid rar'ed torrents
# they are always compressed in a rar archive no matter what files you select
auto_delete_rar_torrents: true
# api_timeout_secs: 60

expose_full_path: true

# if true, during zurg initialization, it will fetch all downloads to unrestrict links faster
# it will also mount your download links in a special directory
#use_download_cache: true

# BEWARE! THERE CAN ONLY BE 1 INSTANCE OF ZURG THAT SHOULD REPAIR YOUR TORRENTS
enable_repair: true

# this is useful for ensuring Plex adds your new content immediately
# uncomment the next line for triggering a partial scan
# on_library_update: sh plex_update.sh "$@"
# if on Windows...
on_library_update: '& .\plex_update.ps1 $args'
#on_library_update: |
#  for arg in "$@"
#  do
#     echo "detected update on: $arg"
#  done

# buffer size when zurg is streaming files
#network_buffer_size: 1048576 # 1 MiB

# true = send link to rclone and rclone will stream the file
# false = zurg will stream the file
serve_from_rclone: false

# true = zurg will check if the link is really working
# only relevant if serve_from_rclone is set to true
# as it already does this all the time if serve_from_rclone is false
verify_download_link: false

# force connect to real-debrid ipv6 addresses
# useful if you are blocked
force_ipv6: false

# sleep time after getting a 429 from Real-Debrid API
#rate_limit_sleep_secs: 6

# time to wait before timing out
#realdebrid_timeout_secs: 60

# api response failures until considered failed
#retries_until_failed: 5

# use the fastest hosts from your location
# Run ./zurg network-test
# preferred_hosts:
#   - 20.download.real-debrid.com
#   - 21.download.real-debrid.com
#   - 22.download.real-debrid.com
#   - 23.download.real-debrid.com
#   - 30.download.real-debrid.com
#   - 31.download.real-debrid.com
#   - 32.download.real-debrid.com
#   - 34.download.real-debrid.com
#   - 40.download.real-debrid.com

# List of directory definitions and their filtering rules
directories:
  # Configuration for anime shows

  shows:
    group: media
    group_order: 20
    filters:
      - has_episodes: true  # intelligent detection of episode files inside a torrent

  movies:
    group: media  # because anime, shows and movies are in the same group,
    group_order: 30 # and anime and shows has a lower group_order number than movies, all torrents that doesn't fall into the previous 2 will fall into movies
    only_show_the_biggest_file: true # let's not show the other files besides the movie itself
    filters:
      - regex: /.*/ # you cannot leave a directory without filters because it will not have any torrents in it

**Logs**
Upload your logs by going to http://ZURGIP:9999/logs/upload and paste the link here
https://0x0.st/HDZ_.log

If you are running it in Docker, your container logs will also help.

**Rclone Configuration**
Attach or detail your `rclone.conf`.
@echo off
REM Change directory and start Rclone
cd "C:\Users\xxx\Desktop\zurg-testing"
rclone mount zurg: T: --dir-cache-time 10s --vfs-cache-mode full --vfs-cache-max-age 168h --vfs-cache-max-size 200G  --async-read --vfs-read-ahead 128M --vfs-read-chunk-size 64M --vfs-read-chunk-size-limit 2G --use-mmap --buffer-size=64M --cache-dir=d:/rclone/cache

**Screenshots**

![image](https://github.com/debridmediamanager/zurg-testing/assets/23236691/610082e8-56c3-40e5-ad7c-fa6796259f03)
![image](https://github.com/debridmediamanager/zurg-testing/assets/23236691/e6c8376a-d0cd-40e3-a79e-862f439fc44a)

**Comment by fatbob01** [comment]
another observation, if i restart zurg, shows that were missing come back and play fine in plex (if they are already there) as long as I dont run a scan in plex, which then removes them in zurg.

**Comment by yowmamasita** [comment]
Tried resolving this on `v0.9.3-hotfix.4` please check

**Comment by deepvalu** [comment]
I'm on the latest version and this appears to still be happening. Zurg says the torrent is repaired but it's gone.

**Comment by fatbob01** [comment]
issue persists unfortunately 
https://0x0.st/HDa_.log

**Comment by fatbob01** [comment]
seems to be resolved for me in v5
