### ISSUE TITLE
Bug: New files are not activating a refresh

### ISSUE THREAD

**Issue by Varming73** [debridmediamanager/zurg-testing#61]
I just came home and several files were waiting in RDT. I check on the main RD site and the files were downloaded perfectly. In the Zurg logs no changes were logged so it seems like Zurg still don't pull updates after a while. After restarting the Zurg container everything waiting in RDT became finished as the files were now found in Zurg.

So something still doesn't update in Zurg. I guess I have to revert to 0.9.2hotfix4 again. Seems like an unstable solution to restart the container every 10 min or something.

**Comment by drahmed86** [comment]
Many of us have this issue specifically and ig yow's on it

**Comment by Varming73** [comment]
The issue was closed as solved this morning, so I hope it will be resolved this time instead.

**Comment by yowmamasita** [comment]
@Varming73 workaround until i send the fix: disable repair

**Comment by yowmamasita** [comment]
Tried resolving this on `v0.9.3-hotfix.4` please check

**Comment by drahmed86** [comment]
Unfortunately after a while zurg latest running, the RD updates not reflected in zurg

**Comment by drahmed86** [comment]
https://0x0.st/HDa-.log

**Comment by Varming73** [comment]
@drahmed86 when logging at the log: What should have happend? It's difficult to know what to look for when it isn't there.

Secondly: Be aware then you share the log that if somebody copy/paste the RD URLs it will be seen as somebody using your RD from a different IP, which can make RD close your account.

**Comment by Varming73** [comment]
@yowmamasita I just took a look at my own setup and can confirm that in my setup Zurg doesn't refresh after a while either. With log level DEBUG nothing is shown that can explain why. In my config.yml I have this:

```
concurrent_workers: 32
check_for_changes_every_secs: 15
api_timeout_secs: 60
retries_until_failed: 5
rate_limit_sleep_secs: 6
download_timeout_secs: 2
```
I tried the Reboot Refresh Worker but that doesn't work in hotfix4, a new browser tab gets opened but no page is ever shown. It didn't reboot the workers either so it doesn't do anything atm.
I then restarted the container and upon reload everything was there.

So the issue is still not resolved - and in DEBUG nothing in the logs even explain what has happend. Will it help you if I put log level ALL or haven't logging been implemented that will give you anything of use?

**Comment by drahmed86** [comment]
> @drahmed86 when logging at the log: What should have happend? It's difficult to know what to look for when it isn't there.
> 
> Secondly: Be aware then you share the log that if somebody copy/paste the RD URLs it will be seen as somebody using your RD from a different IP, which can make RD close your account.

yea thanks

**Comment by Varming73** [comment]
Saw it in the repo and installed right away, thnx

**Comment by Varming73** [comment]
It still doesn't work. I added the file via RDP. I can see the file in DMM but Zurg doesn't see that file/or refresh to get it. I rebootet the refresh worker which did open the browser tab with the correct text and I saw this in the log:

```
2024-01-30T18:03:08.823Z        INFO    router  Rebooted refresh worker
2024-01-30T18:03:08.823Z        INFO    manager Starting periodic refresh job
2024-01-30T18:03:08.823Z        INFO    manager Stopping periodic refresh job
```

I then restarted the container and the file was finally also in Zurg.

**Comment by drahmed86** [comment]
Latest HF5 works like a treat no need for all that dilemma ya mention

**Comment by Varming73** [comment]
Happy to hear it works for you but that doesn't really help me

**Comment by drahmed86** [comment]
Have ya tried to delete data folder and start from the scratch?!

**Comment by Varming73** [comment]
Nope, I haven't heard that had to be done but am willing to try. Has been running hotfix5 since release and the refresh doesn't work here. Will try to delete if that's recommended.

**Comment by drahmed86** [comment]
Yep give it a shot and stick to the defaults

**Comment by Varming73** [comment]
Confirmed still NOT working. Deleted my Zurg data and fired up hotfix5 again. Several files have been in RD for 4 minutes now and all I see in the log is:

```
2024-01-31T10:04:23.275Z        DEBUG   realdebrid      Got info for torrent KY7JSNYSOAVC4 (progress=0%)
2024-01-31T10:04:23.275Z        DEBUG   manager Saved torrent KY7JSNYSOAVC4 to file
2024-01-31T10:04:23.275Z        DEBUG   realdebrid      Got info for torrent YHNWXBLXC6DCA (progress=0%)
2024-01-31T10:04:23.276Z        DEBUG   manager Saved torrent YHNWXBLXC6DCA to file
2024-01-31T10:04:23.280Z        DEBUG   realdebrid      Got info for torrent YQIDTUQ5UT3ES (progress=0%)
2024-01-31T10:04:23.280Z        DEBUG   manager Saved torrent YQIDTUQ5UT3ES to file
2024-01-31T10:04:23.284Z        DEBUG   realdebrid      Got info for torrent 76DSJJHRTGP6C (progress=0%)
2024-01-31T10:04:23.284Z        DEBUG   manager Saved torrent 76DSJJHRTGP6C to file
2024-01-31T10:04:23.284Z        INFO    manager Fetched info for 5568 torrents
2024-01-31T10:39:33.380Z        INFO    manager Periodic repair started; searching for broken torrents
2024-01-31T10:39:33.386Z        INFO    manager Found 0 broken torrents to repair in total
2024-01-31T10:39:33.386Z        INFO    manager Finished repairing 0 broken torrents
```
So Zurg still doesn't update - and been running less than an hour.

**Comment by drahmed86** [comment]
update:: yep ya're right i can see inconsistent refreshing work of zurg HF5 so disabling the repair feature as a workaround .. lets wait and see lol

**Comment by yowmamasita** [comment]
Can you please try a new revision I sent few minutes ago? `v0.9.3-hotfix.5` @Varming73

**Comment by yowmamasita** [comment]
it should be fixed now on `v0.9.3-hotfix.6` this is it

**Comment by Varming73** [comment]
I've started testing hotfix6 now, will report any errors found related to this issue (fingers crossed)

**Comment by Varming73** [comment]
Running hotfix7 it actually seems like you got the issue fixed. Will close tomorrow if everything is still smooth sailing.

**Comment by yowmamasita** [comment]
Fyi this is already fixed. Please reopen if this is not the case.

**Comment by CounterCultural** [comment]
Hate to be that guy, but I am still having trouble with library rescans on `v0.9.3-final`. I got super excited for a second because it worked for one movie after disabling repair like you mentioned earlier, then right back to needing a manual refresh.

**Comment by CounterCultural** [comment]
Rescan is still super inconsistent on `v0.9.3-final`. Couldn't get it to work at all, then tried disabling repair like mentioned earlier and now it's 2/5 for me
