### ISSUE TITLE
question about real debrid connection limit 

### ISSUE THREAD

**Issue by pharrowboy** [debridmediamanager/zurg-testing#62]
hey i had a question regarding real debrid's 32 connection limit. without using any kind of proxy server does this tool essentially proxy the connection to the drive? like for example is every movie that is transcoded or connected to by a remote plex user connected through your server's ip address? or does the remote user count as 1 connection to the drive created by rclone, and there by 1 connection of 32 limit to real debrid?

if not could that be added via a feature request?

**Comment by yowmamasita** [comment]
32 connection limit is per server, not for the whole real-debrid. it's very hard to reach this generous limit so it shouldn't matter to the user.
