### ISSUE TITLE
Bug: DEBUG logging changed or broken

### ISSUE THREAD

**Issue by Varming73** [debridmediamanager/zurg-testing#64]
I got log level DEBUG but unlike in earlier builds (unsure which as it both builds and commits of builds which makes it hard to track) I can't see for example that the file is being downloaded when played. I got the suspicion that something is wrong with the logging system - which also makes it hard to provide useful logging towards the refresh problem.

**Comment by yowmamasita** [comment]
No that was intended. It was only meant for understanding the part where Plex was being stuck. When i figured out the issue, i removed it. Do you want it returned?

**Comment by Varming73** [comment]
Ah ok, didn't know it was intended and just wanted to raise your awareness to it. I don't need it, thnx
