### ISSUE TITLE
Request: Docker-less option on MacOS

### ISSUE THREAD

**Issue by maybecryptic** [debridmediamanager/zurg-testing#67]
**Feature Description**
It would be helpful to run zurg outside of docker on MacOS.

**Problem and Motivation**
The problem is the docker mount is always empty no matter what I did. I could see the files inside the rclone docker file explorer (in the data folder), so it was working. I just couldn't see the files outside of docker for plex to see and pick up. I tried changing the different mounting options, but it made no difference.

**Comment by yowmamasita** [comment]
after zurg was run, make sure you have the right rclone.conf

```
rclone mount zurgrclone: /Users/xyz/zurgmountpoint --dir-cache-time 1s --allow-other --vfs-cache-mode full
```

**Comment by maybecryptic** [comment]
I'm not following, are we supposed to install and run rclone outside of docker? I don't have a "zurgrclone" in rclone config.
![image](https://github.com/debridmediamanager/zurg-testing/assets/6799090/ab9717b4-fde0-4f4c-8c7a-986d9370f378)

here's what I mean, I can see the files in docker
![image](https://github.com/debridmediamanager/zurg-testing/assets/6799090/a3a83cb8-4a0e-49f1-a729-882c660fcbfd)

yet this is where the mount points and nothing is there
![image](https://github.com/debridmediamanager/zurg-testing/assets/6799090/b1efa41d-7204-44d3-8c5c-77e4215d673c)

**Comment by maybecryptic** [comment]
ok I installed rclone on my host machine and made a new config for `http://localhost:9999/http` and that seems to have done the trick. it'd still be nice to run it natively though so that it runs cleaner and it's a more straightforward setup
