### ISSUE TITLE
Rclone Mount

### ISSUE THREAD

**Issue by arjung24** [debridmediamanager/zurg-testing#78]
I have set the zurg rclone mount under /mnt folder but plex can't see it when trying to create library. Plex can't find the subfolder inside /mnt folder.
![IMG_20240210_205813](https://github.com/debridmediamanager/zurg-testing/assets/68998000/6e44bc06-cbd8-43bf-b3bb-ed430a8cecbc)

**Comment by yowmamasita** [comment]
This is not a zurg issue but a permission issue on rclone, closing
