### ISSUE TITLE
"We have reached the max number of active torrents" message

### ISSUE THREAD

**Issue by Keagel** [debridmediamanager/zurg-testing#92]
Hello!

What does this message actually mean? Is there a limit of how many torrents real-debrid allows?
I logged into my real-debrid account and found the same torrent dozens of time, errored and at the same progress percentage. I've removed all of them but I still have over 200 because I have a big library, and that message remains. Does it mean zurg has a limit of how many items I can actively have in my library?

Thanks!

**Comment by Friday13th87** [comment]
the statement is "active torrents" not only "torrents"
btw in ddm is a function to show and delete duplicates...
